BASIC LINEAR ALGEBRA

Julia's syntax is very similar to other languages but there are some important differences. Define a matrix of random normal varieties

In [15]:
A = rand(1:4, 3, 3)

3×3 Matrix{Int64}:
 4  2  3
 1  4  2
 2  3  2

In [16]:
B = A
C = copy(A)
[ B C]

3×6 Matrix{Int64}:
 4  2  3  4  2  3
 1  4  2  1  4  2
 2  3  2  2  3  2

In [17]:
# Watch out!

A[1] = 17
[B C] # B and A are references to the same memory (better for per)

3×6 Matrix{Int64}:
 17  2  3  4  2  3
  1  4  2  1  4  2
  2  3  2  2  3  2

and a vector of ones

In [18]:
x = ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

Notice that A has a type Array[Flloat64,2] but x has type Array[Float,1]. Julia defines the aliases Vector[Type]=Array[Type,1] and matrix[Type]=Array[Type,2] in Julia.

Many of the basics operations are the same as in other languages.

Multiplication

In [19]:
b = A*x

3-element Vector{Float64}:
 22.0
  7.0
  7.0

Transposition

As in the other languages A' is the conjugate transpose whereas A.' is just the transpose

In [20]:
Asym = A + A'

3×3 Matrix{Int64}:
 34  3  5
  3  8  5
  5  5  4

Transposed Multiplication

Julia allowsus to write this without *

In [21]:
Apd = A'A

3×3 Matrix{Int64}:
 294  44  57
  44  29  20
  57  20  17

Solving linear system

The problem Ax=b for square A is solved by the \function

In [22]:
A\b

3-element Vector{Float64}:
 0.9999999999999998
 0.9999999999999994
 1.0000000000000013

Overdetermined systems

When A is tall the \function calculates the least square solution.

In [23]:
# Keep all rows and only the first 2 columns of 'A' to generate
Atall = A[:,1:2]
display(Atall)
Atall\b

3×2 Matrix{Int64}:
 17  2
  1  4
  2  3

2-element Vector{Float64}:
 1.1172989377845213
 1.5116843702579668

The \function also works for rank deficient least square problems. In this case, the least square solution is not unique and Julia returns the solution with smallest norm.

In [24]:
A = randn(3, 3)

3×3 Matrix{Float64}:
  1.25645  -0.526378  -1.88324
  2.54422   1.43119   -1.26838
 -1.87001   1.9746     1.56399

In [25]:
# The outer product of a vector with itself will result in a singular matrix representing a rank deficient least squares problem

[A[:,1] A[:,1]]\b

2-element Vector{Float64}:
 1.4010894353529637
 1.401089435352964

Underdetermined Systems

When A is short the \function returns the minimum norm solution.

In [26]:
# Keep all the columns and only the first 2 rows of 'A' to generate
Ashort = A[1:2,:]
display(Ashort)
Ashort\b[1:2]

2×3 Matrix{Float64}:
 1.25645  -0.526378  -1.88324
 2.54422   1.43119   -1.26838

3-element Vector{Float64}:
  2.016388149782694
 -6.2949570215351045
 -8.577216017591272